// Copyright (c) 2026 Francesco Crimi
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file or at
// https://opensource.org/licenses/MIT.

namespace CiccioSoft.Sqlite.Interop;

/// <summary>
/// Represents SQLite extended error codes.
/// </summary>
public enum SqliteExtendedErrorCode
{
    OK = SqliteResult.OK,
    Error = SqliteResult.Error,
    Internal = SqliteResult.Internal,
    Perm = SqliteResult.Perm,
    Abort = SqliteResult.Abort,
    Busy = SqliteResult.Busy,
    Locked = SqliteResult.Locked,
    NoMem = SqliteResult.NoMem,
    ReadOnly = SqliteResult.ReadOnly,
    Interrupt = SqliteResult.Interrupt,
    IOErr = SqliteResult.IOErr,
    Corrupt = SqliteResult.Corrupt,
    NotFound = SqliteResult.NotFound,
    Full = SqliteResult.Full,
    CantOpen = SqliteResult.CantOpen,
    Protocol = SqliteResult.Protocol,
    Empty = SqliteResult.Empty,
    Schema = SqliteResult.Schema,
    TooBig = SqliteResult.TooBig,
    Constraint = SqliteResult.Constraint,
    Mismatch = SqliteResult.Mismatch,
    Misuse = SqliteResult.Misuse,
    NoLfs = SqliteResult.NoLfs,
    Auth = SqliteResult.Auth,
    Format = SqliteResult.Format,
    Range = SqliteResult.Range,
    NotADb = SqliteResult.NotADb,
    Notice = SqliteResult.Notice,
    Warning = SqliteResult.Warning,
    Row = SqliteResult.Row,
    Done = SqliteResult.Done,

    ErrorMissingCollSeq = SqliteResult.Error | (1 << 8),
    ErrorRetry = SqliteResult.Error | (2 << 8),
    ErrorSnapshot = SqliteResult.Error | (3 << 8),
    IOErrRead = SqliteResult.IOErr | (1 << 8),
    IOErrShortRead = SqliteResult.IOErr | (2 << 8),
    IOErrWrite = SqliteResult.IOErr | (3 << 8),
    IOErrFsync = SqliteResult.IOErr | (4 << 8),
    IOErrDirFsync = SqliteResult.IOErr | (5 << 8),
    IOErrTruncate = SqliteResult.IOErr | (6 << 8),
    IOErrFstat = SqliteResult.IOErr | (7 << 8),
    IOErrUnlock = SqliteResult.IOErr | (8 << 8),
    IOErrRdlock = SqliteResult.IOErr | (9 << 8),
    IOErrDelete = SqliteResult.IOErr | (10 << 8),
    IOErrBlocked = SqliteResult.IOErr | (11 << 8),
    IOErrNoMem = SqliteResult.IOErr | (12 << 8),
    IOErrAccess = SqliteResult.IOErr | (13 << 8),
    IOErrCheckReservedLock = SqliteResult.IOErr | (14 << 8),
    IOErrLock = SqliteResult.IOErr | (15 << 8),
    IOErrClose = SqliteResult.IOErr | (16 << 8),
    IOErrDirClose = SqliteResult.IOErr | (17 << 8),
    IOErrShmOpen = SqliteResult.IOErr | (18 << 8),
    IOErrShmSize = SqliteResult.IOErr | (19 << 8),
    IOErrShmLock = SqliteResult.IOErr | (20 << 8),
    IOErrShmMap = SqliteResult.IOErr | (21 << 8),
    IOErrSeek = SqliteResult.IOErr | (22 << 8),
    IOErrDeleteNoEnt = SqliteResult.IOErr | (23 << 8),
    IOErrMmap = SqliteResult.IOErr | (24 << 8),
    IOErrGetTempPath = SqliteResult.IOErr | (25 << 8),
    IOErrConvPath = SqliteResult.IOErr | (26 << 8),
    IOErrVnode = SqliteResult.IOErr | (27 << 8),
    IOErrAuth = SqliteResult.IOErr | (28 << 8),
    IOErrBeginAtomic = SqliteResult.IOErr | (29 << 8),
    IOErrCommitAtomic = SqliteResult.IOErr | (30 << 8),
    IOErrRollbackAtomic = SqliteResult.IOErr | (31 << 8),
    IOErrData = SqliteResult.IOErr | (32 << 8),
    IOErrCorruptFs = SqliteResult.IOErr | (33 << 8),
    IOErrInPage = SqliteResult.IOErr | (34 << 8),
    LockedSharedCache = SqliteResult.Locked | (1 << 8),
    LockedVtab = SqliteResult.Locked | (2 << 8),
    BusyRecovery = SqliteResult.Busy | (1 << 8),
    BusySnapshot = SqliteResult.Busy | (2 << 8),
    BusyTimeout = SqliteResult.Busy | (3 << 8),
    CantOpenNoTempDir = SqliteResult.CantOpen | (1 << 8),
    CantOpenIsDir = SqliteResult.CantOpen | (2 << 8),
    CantOpenFullPath = SqliteResult.CantOpen | (3 << 8),
    CantOpenConvPath = SqliteResult.CantOpen | (4 << 8),
    CantOpenDirtyWal = SqliteResult.CantOpen | (5 << 8),
    CantOpenSymlink = SqliteResult.CantOpen | (6 << 8),
    CorruptVtab = SqliteResult.Corrupt | (1 << 8),
    CorruptSequence = SqliteResult.Corrupt | (2 << 8),
    CorruptIndex = SqliteResult.Corrupt | (3 << 8),
    ReadOnlyRecovery = SqliteResult.ReadOnly | (1 << 8),
    ReadOnlyCantLock = SqliteResult.ReadOnly | (2 << 8),
    ReadOnlyRollback = SqliteResult.ReadOnly | (3 << 8),
    ReadOnlyDbMoved = SqliteResult.ReadOnly | (4 << 8),
    ReadOnlyCantInit = SqliteResult.ReadOnly | (5 << 8),
    ReadOnlyDirectory = SqliteResult.ReadOnly | (6 << 8),
    AbortRollback = SqliteResult.Abort | (2 << 8),
    ConstraintCheck = SqliteResult.Constraint | (1 << 8),
    ConstraintCommitHook = SqliteResult.Constraint | (2 << 8),
    ConstraintForeignKey = SqliteResult.Constraint | (3 << 8),
    ConstraintFunction = SqliteResult.Constraint | (4 << 8),
    ConstraintNotNull = SqliteResult.Constraint | (5 << 8),
    ConstraintPrimaryKey = SqliteResult.Constraint | (6 << 8),
    ConstraintTrigger = SqliteResult.Constraint | (7 << 8),
    ConstraintUnique = SqliteResult.Constraint | (8 << 8),
    ConstraintVtab = SqliteResult.Constraint | (9 << 8),
    ConstraintRowId = SqliteResult.Constraint | (10 << 8),
    ConstraintPinned = SqliteResult.Constraint | (11 << 8),
    ConstraintDataType = SqliteResult.Constraint | (12 << 8),
    NoticeRecoverWal = SqliteResult.Notice | (1 << 8),
    NoticeRecoverRollback = SqliteResult.Notice | (2 << 8),
    NoticeRbu = SqliteResult.Notice | (3 << 8),
    WarningAutoIndex = SqliteResult.Warning | (1 << 8),
    AuthUser = SqliteResult.Auth | (1 << 8),
    OkLoadPermanently = SqliteResult.OK | (1 << 8),
    OkSymlink = SqliteResult.OK | (2 << 8)
}
