// <auto-generated>
// This code was automatically generated by ClangSharpPInvokeGenerator.
// </auto-generated>
// 
// Copyright (c) 2026 Francesco Crimi. All rights reserved.
// 
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file or at
// https://opensource.org/licenses/MIT.

using System.Runtime.CompilerServices;

[assembly: DisableRuntimeMarshalling]
